api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        json: ['application/json']
        jsonld: ['application/json+ld']
        html: ['text/html']
        multipart: ['multipart/form-data']
    swagger:
        versions: [3]
